print('''
          ASSALOMU ALAYKUM AZIZ YURTDOSHLAR 
      BU DASTUR BELGILARNI BINARY, HEXADECIMAL VA OTICAN TIZIMALRGA SHIFRLAYDI VA DISHIFRLAYDI
''')
print('''Dasturni ishlatish uchun parolni kiriting: ''')

while True:
    parol = input(">>>: ")
    if parol != "BEKFURR IS BEST FOREVER":
        print("Parol noto'g'ri!")
    else:
        par = True
        break    
        

while par == True:
    print('''
          DASTUR AMALINI TANLANG:
          1.text to binaty
          2.text to octal
          3.text to hexadecimal
          4. binaty to text
          5. octal to text
          6. hexadecimal to text
          0= DASTURNI TOXTATISH''')
    
    tanlov = int(input(">>>: "))

    if tanlov == 1:
        b = input("Textni kiriting: ")
        b = b.replace("A", "1000001 ")
        b = b.replace("B", "1000010 ")   
        b = b.replace("C", "1000011 ")
        b = b.replace("D", "1000100 ")
        b = b.replace("E", "1000101 ")
        b = b.replace("F", "1000110 ")
        b = b.replace("G", "1000111 ")
        b = b.replace("H", "1001000 ")
        b = b.replace("I", "1001001 ")
        b = b.replace("J", "1001010 ")
        b = b.replace("K", "1001011 ")
        b = b.replace("L", "1001100 ")
        b = b.replace("M", "1001101 ")
        b = b.replace("N", "1001110 ")
        b = b.replace("O", "1001111 ")
        b = b.replace("P", "1010000 ")
        b = b.replace("Q", "1010001 ")
        b = b.replace("R", "1010010 ")
        b = b.replace("S", "1010011 ")
        b = b.replace("T", "1010100 ")
        b = b.replace("U", "1010101 ")
        b = b.replace("V", "1010110 ")
        b = b.replace("W", "1010111 ")
        b = b.replace("X", "1011000 ")
        b = b.replace("Y", "1011001 ")
        b = b.replace("Z", "1011010 ")
        b = b.replace("a", "1100001 ")
        b = b.replace("b", "1100010 ")
        b = b.replace("c", "1100011 ")
        b = b.replace("d", "1100100 ")
        b = b.replace("e", "1100101 ")
        b = b.replace("f", "1100110 ")
        b = b.replace("g", "1100111 ")
        b = b.replace("h", "1101000 ")
        b = b.replace("i", "1101001 ")
        b = b.replace("j", "1101010 ")
        b = b.replace("k", "1101011 ")
        b = b.replace("l", "1101100 ")
        b = b.replace("m", "1101101 ")
        b = b.replace("n", "1101110 ")
        b = b.replace("o", "1101111 ")
        b = b.replace("p", "1110000 ")
        b = b.replace("q", "1110001 ")
        b = b.replace("r", "1110010 ")
        b = b.replace("s", "1110011 ")
        b = b.replace("t", "1110100 ")
        b = b.replace("u", "1110101 ")
        b = b.replace("v", "1110110 ")
        b = b.replace("w", "1110111 ")
        b = b.replace("x", "1111000 ")
        b = b.replace("y", "1111001 ")
        b = b.replace("z", "1111010 ")
        print("Text:", b)
    elif tanlov == 2:
        o = input("Textni kiriting: ")
        o = o.replace("A", "101 ")
        o = o.replace("B", "102 ") 
        o = o.replace("C", "103 ")
        o = o.replace("D", "104 ")
        o = o.replace("E", "105 ")
        o = o.replace("F", "106 ")
        o = o.replace("G", "107 ")
        o = o.replace("H", "110 ")
        o = o.replace("I", "111 ")
        o = o.replace("J", "112 ")
        o = o.replace("K", "113 ")
        o = o.replace("L", "114 ")
        o = o.replace("M", "115 ")
        o = o.replace("N", "116 ")
        o = o.replace("O", "117 ")
        o = o.replace("P", "120 ")
        o = o.replace("Q", "121 ")
        o = o.replace("R", "122 ")
        o = o.replace("S", "123 ")
        o = o.replace("T", "124 ")
        o = o.replace("U", "125 ")
        o = o.replace("V", "126 ")
        o = o.replace("W", "127 ")
        o = o.replace("X", "130 ")
        o = o.replace("Y", "131 ")
        o = o.replace("Z", "132 ")
        o = o.replace("a", "133 ")
        o = o.replace("b", "134 ")
        o = o.replace("c", "135 ")
        o = o.replace("d", "136 ")
        o = o.replace("e", "137 ")
        o = o.replace("f", "140 ")
        o = o.replace("g", "141 ")
        o = o.replace("h", "142 ")
        o = o.replace("i", "143 ")
        o = o.replace("j", "144 ")
        o = o.replace("k", "145 ")
        o = o.replace("l", "146 ")
        o = o.replace("m", "147 ")
        o = o.replace("n", "150 ")
        o = o.replace("o", "151 ")
        o = o.replace("p", "152 ")
        o = o.replace("q", "153 ")
        o = o.replace("r", "154 ")
        o = o.replace("s", "155 ")
        o = o.replace("t", "156 ")
        o = o.replace("u", "157 ")
        o = o.replace("v", "160 ")
        o = o.replace("w", "161 ")
        o = o.replace("x", "162 ")
        o = o.replace("y", "163 ")
        o = o.replace("z", "164 ")


        


        print("Text:", o)
    elif tanlov == 3:  
        h = input("Textni kiriting: ")
        h = h.replace("A", "41 ")
        h = h.replace("B", "42 ")
        h = h.replace("C", "43 ")
        h = h.replace("D", "44 ")
        h = h.replace("E", "45 ")
        h = h.replace("F", "46 ")
        h = h.replace("G", "47 ")
        h = h.replace("H", "48 ")
        h = h.replace("I", "49 ")
        h = h.replace("J", "4A ")
        h = h.replace("K", "4B ")
        h = h.replace("L", "4C ")
        h = h.replace("M", "4D ")
        h = h.replace("N", "4E ")
        h = h.replace("O", "4F ")
        h = h.replace("P", "50 ")
        h = h.replace("Q", "51 ")
        h = h.replace("R", "52 ")
        h = h.replace("S", "53 ")
        h = h.replace("T", "54 ")
        h = h.replace("U", "55 ")
        h = h.replace("V", "56 ")
        h = h.replace("W", "57 ")
        h = h.replace("X", "58 ")
        h = h.replace("Y", "59 ")
        h = h.replace("Z", "5A ")
        h = h.replace("a", "61 ")
        h = h.replace("b", "62 ")
        h = h.replace("c", "63 ")
        h = h.replace("d", "64 ")
        h = h.replace("e", "65 ")
        h = h.replace("f", "66 ")
        h = h.replace("g", "67 ")
        h = h.replace("h", "68 ")
        h = h.replace("i", "69 ")
        h = h.replace("j", "6A ")
        h = h.replace("k", "6B ")
        h = h.replace("l", "6C ")
        h = h.replace("m", "6D ")
        h = h.replace("n", "6E ")
        h = h.replace("o", "6F ")
        h = h.replace("p", "70 ")
        h = h.replace("q", "71 ")
        h = h.replace("r", "72 ")
        h = h.replace("s", "73 ")
        h = h.replace("t", "74 ")
        h = h.replace("u", "75 ")
        h = h.replace("v", "76 ")
        h = h.replace("w", "77 ")
        h = h.replace("x", "78 ")
        h = h.replace("y", "79 ")
        h = h.replace("z", "7A ")
        print("Text:", h)
    elif tanlov == 4:
        t_b = input("Textni kiriting: ")
        t_b = t_b.replace( "1000001", "A")
        t_b = t_b.replace( "1000010", "B")
        t_b = t_b.replace( "1000011", "C")
        t_b = t_b.replace( "1000100", "D")
        t_b = t_b.replace( "1000101", "E")
        t_b = t_b.replace( "1000110", "F")
        t_b = t_b.replace( "1000111", "G")
        t_b = t_b.replace( "1001000", "H")
        t_b = t_b.replace( "1001001", "I")
        t_b = t_b.replace( "1001010", "J")
        t_b = t_b.replace( "1001011", "K")
        t_b = t_b.replace( "1001100", "L")
        t_b = t_b.replace( "1001101", "M")
        t_b = t_b.replace( "1001110", "N")
        t_b = t_b.replace( "1001111", "O")
        t_b = t_b.replace( "1010000", "P")
        t_b = t_b.replace( "1010001", "Q")
        t_b = t_b.replace( "1010010", "R")
        t_b = t_b.replace( "1010011", "S")
        t_b = t_b.replace( "1010100", "T")
        t_b = t_b.replace( "1010101", "U")
        t_b = t_b.replace( "1010110", "V")
        t_b = t_b.replace( "1010111", "W")
        t_b = t_b.replace( "1011000", "X")
        t_b = t_b.replace( "1011001", "Y")
        t_b = t_b.replace( "1011010", "Z")
        t_b = t_b.replace( "1100001", "a")
        t_b = t_b.replace( "1100010", "b")
        t_b = t_b.replace( "1100011", "c")
        t_b = t_b.replace( "1100100", "d")
        t_b = t_b.replace( "1100101", "e")
        t_b = t_b.replace( "1100110", "f")
        t_b = t_b.replace( "1100111", "g")
        t_b = t_b.replace( "1101000", "h")
        t_b = t_b.replace( "1101001", "i")
        t_b = t_b.replace( "1101010", "j")
        t_b = t_b.replace( "1101011", "k")
        t_b = t_b.replace( "1101100", "l")
        t_b = t_b.replace( "1101101", "m")
        t_b = t_b.replace( "1101110", "n")
        t_b = t_b.replace( "1101111", "o")
        t_b = t_b.replace( "1110000", "p")
        t_b = t_b.replace( "1110001", "q")
        t_b = t_b.replace( "1110010", "r")
        t_b = t_b.replace( "1110011", "s")
        t_b = t_b.replace( "1110100", "t")
        t_b = t_b.replace( "1110101", "u")
        t_b = t_b.replace( "1110110", "v")
        t_b = t_b.replace( "1110111", "w")
        t_b = t_b.replace( "1111000", "x")
        t_b = t_b.replace( "1111001", "y")
        t_b = t_b.replace( "1111010", "z")
        print("Text:", t_b)
    elif tanlov == 5:
        t_u = input("Textni kiriting: ")
        t_u = t_u.replace("101", "A")
        t_u = t_u.replace("102", "B")
        t_u = t_u.replace("103", "C")
        t_u = t_u.replace("104", "D")
        t_u = t_u.replace("105", "E")
        t_u = t_u.replace("106", "F")
        t_u = t_u.replace("107", "G")
        t_u = t_u.replace("110", "H")
        t_u = t_u.replace("111", "I")
        t_u = t_u.replace("112", "J")
        t_u = t_u.replace("113", "K")
        t_u = t_u.replace("114", "L")
        t_u = t_u.replace("115", "M")
        t_u = t_u.replace("116", "N")
        t_u = t_u.replace("117", "O")
        t_u = t_u.replace("120", "P")
        t_u = t_u.replace("121", "Q")
        t_u = t_u.replace("122", "R")
        t_u = t_u.replace("123", "S")
        t_u = t_u.replace("124", "T")
        t_u = t_u.replace("125", "U")
        t_u = t_u.replace("126", "V")
        t_u = t_u.replace("127", "W")
        t_u = t_u.replace("130", "X")
        t_u = t_u.replace("131", "Y")
        t_u = t_u.replace("132", "Z")
        t_u = t_u.replace("133", "a")
        t_u = t_u.replace("134", "b")
        t_u = t_u.replace("135", "c")
        t_u = t_u.replace("136", "d")
        t_u = t_u.replace("137", "e")
        t_u = t_u.replace("140", "f")
        t_u = t_u.replace("141", "g")
        t_u = t_u.replace("142", "h")
        t_u = t_u.replace("143", "i")
        t_u = t_u.replace("144", "j")
        t_u = t_u.replace("145", "k")
        t_u = t_u.replace("146", "l")
        t_u = t_u.replace("147", "m")
        t_u = t_u.replace("150", "n")
        t_u = t_u.replace("151", "o")
        t_u = t_u.replace("152", "p")
        t_u = t_u.replace("153", "q")
        t_u = t_u.replace("154", "r")
        t_u = t_u.replace("155", "s")
        t_u = t_u.replace("156", "t")
        t_u = t_u.replace("157", "u")
        t_u = t_u.replace("160", "v")
        t_u = t_u.replace("161", "w")
        t_u = t_u.replace("162", "x")
        t_u = t_u.replace("163", "y")
        t_u = t_u.replace("164", "z")
        print("Text:", t_u)
    elif tanlov == 6:
        t_h = input("Textni kiriting: ")
        t_h = t_h.replace("41", "A")
        t_h = t_h.replace("42", "B")
        t_h = t_h.replace("43", "C")
        t_h = t_h.replace("44", "D")
        t_h = t_h.replace("45", "E")
        t_h = t_h.replace("46", "F")
        t_h = t_h.replace("47", "G")
        t_h = t_h.replace("48", "H")
        t_h = t_h.replace("49", "I")
        t_h = t_h.replace("4A", "J")
        t_h = t_h.replace("4B", "K")
        t_h = t_h.replace("4C", "L")
        t_h = t_h.replace("4D", "M")
        t_h = t_h.replace("4E", "N")
        t_h = t_h.replace("4F", "O")
        t_h = t_h.replace("50", "P")
        t_h = t_h.replace("51", "Q")
        t_h = t_h.replace("52", "R")
        t_h = t_h.replace("53", "S")
        t_h = t_h.replace("54", "T")
        t_h = t_h.replace("55", "U")
        t_h = t_h.replace("56", "V")
        t_h = t_h.replace("57", "W")
        t_h = t_h.replace("58", "X")
        t_h = t_h.replace("59", "Y")
        t_h = t_h.replace("5A", "Z")
        t_h = t_h.replace("61", "a")
        t_h = t_h.replace("62", "b")
        t_h = t_h.replace("63", "c")
        t_h = t_h.replace("64", "d")
        t_h = t_h.replace("65", "e")
        t_h = t_h.replace("66", "f")
        t_h = t_h.replace("67", "g")
        t_h = t_h.replace("68", "h")
        t_h = t_h.replace("69", "i")
        t_h = t_h.replace("6A", "j")
        t_h = t_h.replace("6B", "k")
        t_h = t_h.replace("6C", "l")
        t_h = t_h.replace("6D", "m")
        t_h = t_h.replace("6E", "n")
        t_h = t_h.replace("6F", "o")
        t_h = t_h.replace("70", "p")
        t_h = t_h.replace("71", "q")
        t_h = t_h.replace("72", "r")
        t_h = t_h.replace("73", "s")
        t_h = t_h.replace("74", "t")
        t_h = t_h.replace("75", "u")
        t_h = t_h.replace("76", "v")
        t_h = t_h.replace("77", "w")
        t_h = t_h.replace("78", "x")
        t_h = t_h.replace("79", "y")
        t_h = t_h.replace("7A", "z")
        print("Text:", t_h)
    elif tanlov == 0:
        break
    else:
        print("ERROR")












              


    
                      

     